version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_locale_database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_locale_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_locale_pgadmin
    depends_on:
      - db
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

volumes:
  postgres_locale_data: